name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    
    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

      - name: Stop old containers
        run: docker compose down || true

      - name: Start containers
        run: docker compose up -d
